FROM 047590332772.dkr.ecr.eu-central-1.amazonaws.com/nodejs:16

WORKDIR /usr/src/app

ARG PORT
ENV PORT=$PORT
ENV MAX_DOCUMENTS=4
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN
ARG API_ENV
ENV API_ENV=$API_ENV
ARG SECRET_ID
ENV SECRET_ID=$SECRET_ID
ARG AWS_REGION
ENV AWS_REGION=$AWS_REGION
ARG BUCKET_NAME
ENV BUCKET_NAME=$BUCKET_NAME
ARG API_HOST
ENV API_HOST=$API_HOST
ARG RECORDS_FOLDER
ENV RECORDS_FOLDER=$RECORDS_FOLDER
ARG AVATARS_FOLDER
ENV AVATARS_FOLDER=$AVATARS_FOLDER
ARG INSURANCE_FOLDER
ENV INSURANCE_FOLDER=$INSURANCE_FOLDER
ARG MONGO_URI
ENV MONGO_URI=$MONGO_URI

COPY package*.json ./

RUN npm install
RUN npm run build

COPY . .

RUN npm run migrate

EXPOSE $PORT

CMD [ "npm", "run", "start:prod" ]
